public with sharing class VFCallAnotherVFButtonCOntroller {
    //ApexPages.StandardController returnPage = null;//page to return after submit
   

    //constructor
    public VFCallAnotherVFButtonCOntroller(ApexPages.StandardController controller) {
        //returnPage = controller;
    }

/* 
    public PageReference callAnotherVFPage() {
        // get the current account record id
        Id accountId = ApexPages.currentPage().getParameters().get('id');
        // create a new page reference for the other VF page
        PageReference pr = Page.VFCreateersonAccountButton;
        // pass the account id as a parameter
        pr.getParameters().put('accountId', accountId);
        // return the page reference
        return pr;
    } */
    


}